version: "3.8"

networks:
  dev:
    driver: bridge
services:
  web:
    build: ./prubliceringlabb1
    ports:
      - 3000:3000
    networks:
      - dev
  api:
    build: ./
    ports:
      - 8080:80
    networks:
      - dev
